# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE"

# Include any dependencies generated for this target.
include src_dir/CMakeFiles/../grub-customizer.dir/depend.make

# Include the progress variables for this target.
include src_dir/CMakeFiles/../grub-customizer.dir/progress.make

# Include the compile flags for this target's objects.
include src_dir/CMakeFiles/../grub-customizer.dir/flags.make

src_dir/CMakeFiles/../grub-customizer.dir/confparser.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/confparser.o: src_dir/confparser.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/confparser.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/confparser.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/confparser.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/confparser.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/confparser.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/confparser.cpp" > CMakeFiles/../grub-customizer.dir/confparser.i

src_dir/CMakeFiles/../grub-customizer.dir/confparser.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/confparser.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/confparser.cpp" -o CMakeFiles/../grub-customizer.dir/confparser.s

src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/confparser.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.provides.build

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o: src_dir/grubconfig.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/grubconfig.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconfig.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/grubconfig.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconfig.cpp" > CMakeFiles/../grub-customizer.dir/grubconfig.i

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/grubconfig.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconfig.cpp" -o CMakeFiles/../grub-customizer.dir/grubconfig.s

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.provides.build

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o: src_dir/grubconf_ui_gtk.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconf_ui_gtk.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconf_ui_gtk.cpp" > CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.i

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grubconf_ui_gtk.cpp" -o CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.s

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.provides.build

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o: src_dir/gtk-client.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/gtk-client.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/gtk-client.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/gtk-client.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/gtk-client.cpp" > CMakeFiles/../grub-customizer.dir/gtk-client.i

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/gtk-client.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/gtk-client.cpp" -o CMakeFiles/../grub-customizer.dir/gtk-client.s

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.provides.build

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o: src_dir/libproxy.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/libproxy.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxy.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/libproxy.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxy.cpp" > CMakeFiles/../grub-customizer.dir/libproxy.i

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/libproxy.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxy.cpp" -o CMakeFiles/../grub-customizer.dir/libproxy.s

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.provides.build

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o: src_dir/CMakeFiles/../grub-customizer.dir/flags.make
src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o: src_dir/libproxyscript_parser.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/CMakeFiles" $(CMAKE_PROGRESS_6)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o -c "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxyscript_parser.cpp"

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../grub-customizer.dir/libproxyscript_parser.i"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxyscript_parser.cpp" > CMakeFiles/../grub-customizer.dir/libproxyscript_parser.i

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../grub-customizer.dir/libproxyscript_parser.s"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/libproxyscript_parser.cpp" -o CMakeFiles/../grub-customizer.dir/libproxyscript_parser.s

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.requires:
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.requires

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.provides: src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.requires
	$(MAKE) -f src_dir/CMakeFiles/../grub-customizer.dir/build.make src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.provides.build
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.provides

src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.provides.build: src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.provides.build

# Object files for target ../grub-customizer
__/grub__customizer_OBJECTS = \
"CMakeFiles/../grub-customizer.dir/confparser.o" \
"CMakeFiles/../grub-customizer.dir/grubconfig.o" \
"CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o" \
"CMakeFiles/../grub-customizer.dir/gtk-client.o" \
"CMakeFiles/../grub-customizer.dir/libproxy.o" \
"CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o"

# External object files for target ../grub-customizer
__/grub__customizer_EXTERNAL_OBJECTS =

src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/confparser.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/build.make
src_dir/../grub-customizer: src_dir/CMakeFiles/../grub-customizer.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../grub-customizer"
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../grub-customizer.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src_dir/CMakeFiles/../grub-customizer.dir/build: src_dir/../grub-customizer
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/build

src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/confparser.o.requires
src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/grubconfig.o.requires
src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/grubconf_ui_gtk.o.requires
src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/gtk-client.o.requires
src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/libproxy.o.requires
src_dir/CMakeFiles/../grub-customizer.dir/requires: src_dir/CMakeFiles/../grub-customizer.dir/libproxyscript_parser.o.requires
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/requires

src_dir/CMakeFiles/../grub-customizer.dir/clean:
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" && $(CMAKE_COMMAND) -P CMakeFiles/../grub-customizer.dir/cmake_clean.cmake
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/clean

src_dir/CMakeFiles/../grub-customizer.dir/depend:
	cd "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE" "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE" "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir" "/home/daniel/Dokumente/Grubconfig/2. Versuch/CMAKE/src_dir/grub-customizer.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : src_dir/CMakeFiles/../grub-customizer.dir/depend

