# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

src_dir/grubcfg-proxy.dir/confparser.o: src_dir/confparser.cpp
src_dir/grubcfg-proxy.dir/confparser.o: src_dir/confparser.h

src_dir/grubcfg-proxy.dir/grubcfg_proxy.o: src_dir/confparser.h
src_dir/grubcfg-proxy.dir/grubcfg_proxy.o: src_dir/grubcfg_proxy.cpp
src_dir/grubcfg-proxy.dir/grubcfg_proxy.o: src_dir/libproxy.h

src_dir/grubcfg-proxy.dir/libproxy.o: src_dir/confparser.h
src_dir/grubcfg-proxy.dir/libproxy.o: src_dir/libproxy.cpp
src_dir/grubcfg-proxy.dir/libproxy.o: src_dir/libproxy.h

src_dir/grubcfg-proxy.dir/libproxyscript_parser.o: src_dir/libproxyscript_parser.cpp
src_dir/grubcfg-proxy.dir/libproxyscript_parser.o: src_dir/libproxyscript_parser.h

